app:
  name: "Go Clean Architecture"
  version: "1.0.0"
  port: "8080"
  environment: "development"
  timeout: 5 # seconds
  path_prefix: "/api"  # Optional, can be used to set a base path for the application

mongo:
  uri: "mongodb://localhost:27017"
  database: "mydatabase"
  replicaSet: "rs0"
  authSource: "admin"

database:
  type: "postgres"
  postgres:
    host: "localhost"
    port: 5432
    read_host: "localhost"
    read_port: 5432
    write_host: "localhost"
    write_port: 5432
    username: "user"
    password: "password"
  mongo:
    uri: "mongodb://localhost:27017"
    hosts:
      - "localhost"
    ports:
      - 27017
    database: "mydatabase"
    replicaSet: "rs0"
    authSource: "admin"

logging:
  level: "debug"
  format: "json"
  filepath: "./logs/app.log"
  max_size: 10
  max_age: 30
  max_backups: 3
  compress: false
  localTime: true
  conn_max_lifetime: 0 #hour
  conn_max_idle_time: 30 #minute
  health_check_period: 1 #minute


cors:
  enabled: true
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "If-None-Match"]
  exposed_headers: ["Content-Length"]
  allow_credentials: false
  max_age: 86400

metrics:
  enabled: true
  
redis:
  type: "NORMAL"  # or "SENTINEL"
  addrs: "localhost:6379"
  password: ""
  master_name: ""  # Required if type is "SENTINEL"

cache:
  type: "LRU"  # or "FIFO"
  capacity: 1000  # Number of items to keep in cache
  default_ttl: 60  # Time to live for cache items in seconds

jwt:
  secret_key: "your-super-secret-jwt-key-change-in-production"
  expiration: "24h"
  refresh_expiration: "168h" # 7 days
  issuer: "shortlink-api"
  audience: "shortlink-users"