app:
  name: "Go Clean Architecture"
  version: "1.0.0"
  port: "8080"
  environment: "development"
  timeout: 5 # seconds
  path_prefix: "/api"  # Optional, can be used to set a base path for the application

postgres:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"

mongo:
  uri: "mongodb://localhost:27017"
  database: "mydatabase"
  replicaSet: "rs0"
  authSource: "admin"

logging:
  level: "debug"
  format: "json"
  filepath: "./logs/app.log"
  max_size: 10
  max_age: 30
  max_backups: 3
  compress: false
  localTime: true

cors:
  enabled: true
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "If-None-Match"]
  exposed_headers: ["Content-Length"]
  allow_credentials: false
  maxAge: 86400

metrics:
  enabled: true
  