info:
  contact:
    email: duccv@gviet.vn
    name: DucCV
  description: Content service Swagger APIs.
  termsOfService: http://swagger.io/terms/
  title: CONTENT SERVICE APIs
  version: "1.0"
paths:
  /health:
    get:
      description: Returns 200 with {"status":"ok"} when the service is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
  /ready:
    get:
      description: Returns 200 with {"status":"ready"} if service is ready, otherwise
        503 with {"status":"not ready"}
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Readiness Check
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    description: JWT authorization header
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
